### ISSUE TITLE
Private League Access

### ISSUE THREAD

**Issue by tim-sauchuk** [wcrasta/ESPN-Fantasy-Basketball#10]
Thank you for creating an ESPN Fantasy Basketball app. Only other ESPN Fantasy apps I see are football, so kudos. Do you have any plans for integrating with private leagues? I would love to use this app, but I have a private league.

**Comment by wcrasta** [comment]
Hey @tim-sauchuk, thanks for your kind message, I appreciate it. I don't see this app working with private leagues in the near future for the following reasons:

- ESPN does not provide any public APIs for Fantasy Basketball. All the data I use to calculate various rankings and comparisons are obtained through web scraping. If your league is private, the web scraper has no way to access the league data.
- One way the web scraper might be able to access private league data is if I ask the user for their cookie (or ESPN user/pw). Again, since ESPN doesn't have any APIs for authentication, my program would have to take the user's credentials and simulate logging in through a browser automation tool, like Selenium. The user has no way of knowing if I am doing anything malicious with their credentials.
- My league has decided to move away from ESPN to Yahoo, so I likely won't be doing any more development on this project unless it is quick fixes.

So for now, your best bet is to ask your League Manager if he/she can make the league public. I wish ESPN cared more about their developer community!
